# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

require_relative '../../lib/afmotion'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'AppDotNet'

  app.pods do
    pod 'AFNetworking', "~> 2.0.0"
  end
end